# Тема “Вычисления с помощью Numpy”

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1,7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)

In [5]:
mean_a

array([2. , 8.4])

### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [13]:
a_c_1 = a_centered[0:5, 0].copy()

In [14]:
a_c_1

array([-1.,  0.,  1.,  1., -1.])

In [15]:
a_c_2 = a_centered[0:5, 1].copy()

In [16]:
a_c_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [17]:
a_centered_sp = a_c_1 @ a_c_2

In [18]:
a_centered_sp

8.0

In [19]:
n = 5

In [20]:
antwort_3 = (a_centered_sp) / (n - 1)

In [21]:
antwort_3

2.0

### Задание 4

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 3 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [22]:
m = a.transpose()

In [23]:
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [24]:
antwort_4 = np.cov(m)

In [25]:
antwort_4[0,1]

2.0

In [26]:
antwort_3 == antwort_4[0,1]

True

# Тема “Работа с данными в Pandas”

### Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  

[1, 1, 1, 2, 2, 3, 3],

['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],

[450, 300, 350, 500, 450, 370, 290].


In [29]:
import pandas as pd

In [30]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})

In [31]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [32]:
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})

In [33]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id

In [35]:
authors_price = pd.merge(book, authors, on='author_id', how='inner')

In [36]:
authors_price

author_id            book_title  price author_name
0          1           Отцы и дети    450    Тургенев
1          1                 Рудин    300    Тургенев
2          1     Дворянское гнездо    350    Тургенев
3          2      Толстый и тонкий    500       Чехов
4          2       Дама с собачкой    450       Чехов
5          3                 Гроза    370  Островский
6          3  Таланты и поклонники    290  Островский

### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [39]:
top_5 = authors_price.sort_values(by= 'price', ascending= False).head(5).copy()

In [40]:
top_5

author_id         book_title  price author_name
3          2   Толстый и тонкий    500       Чехов
0          1        Отцы и дети    450    Тургенев
4          2    Дама с собачкой    450       Чехов
5          3              Гроза    370  Островский
2          1  Дворянское гнездо    350    Тургенев

### Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [50]:
p_min = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})

p_max = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})

p_mean = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})

authors_stat = pd.concat([p_min, p_max, p_mean], axis = 1)

In [51]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Задание 5

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [64]:
import numpy as np

In [61]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [62]:
authors_price

author_id            book_title  price author_name    cover
0          1           Отцы и дети    450    Тургенев  твердая
1          1                 Рудин    300    Тургенев   мягкая
2          1     Дворянское гнездо    350    Тургенев   мягкая
3          2      Толстый и тонкий    500       Чехов  твердая
4          2       Дама с собачкой    450       Чехов  твердая
5          3                 Гроза    370  Островский   мягкая
6          3  Таланты и поклонники    290  Островский   мягкая

In [65]:
book_info = pd.pivot_table(authors_price, values = 'price', index = ['author_name'], columns = ['cover'], aggfunc = np.sum, fill_value = 0)

In [66]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [67]:
book_info.to_pickle('book_info.pkl')

In [68]:
book_info2 = pd.read_pickle('book_info.pkl')

In [69]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True